export const products = [
  { name: "Bread", category: "Bakery" },
  { name: "Croissants", category: "Bakery" },
  { name: "Cream biscuits", category: "Bakery" },
  { name: "Crackers", category: "Bakery" },
  { name: "Frozen pizza dough", category: "Bakery" },
  { name: "Frozen pizza", category: "Bakery" },
  { name: "Cozonac", category: "Bakery" },
  { name: "Apples", category: "Fruit" },
  { name: "Mango", category: "Fruit" },
  { name: "Pears", category: "Fruit" },
  { name: "Grapes", category: "Fruit" },
  { name: "Bananas", category: "Fruit" },
  { name: "Oranges", category: "Fruit" },
  { name: "Lemons", category: "Fruit" },
  { name: "White cabbage", category: "Vegetables" },
  { name: "Carrots", category: "Vegetables" },
  { name: "Broccoli", category: "Vegetables" },
  { name: "Tomatoes", category: "Vegetables" },
  { name: "Red onions", category: "Vegetables" },
  { name: "White onions", category: "Vegetables" },
  { name: "Spring onions", category: "Vegetables" },
  { name: "Radishes", category: "Vegetables" },
  { name: "Cucumbers", category: "Vegetables" },
  { name: "Kohlrabi", category: "Vegetables" },
  { name: "Celeriac", category: "Vegetables" },
  { name: "Kapia peppers", category: "Vegetables" },
  { name: "Bell peppers", category: "Vegetables" },
  { name: "Hot peppers", category: "Vegetables" },
  { name: "Parsnips", category: "Vegetables" },
  { name: "Parsley root", category: "Vegetables" },
  { name: "Potatoes", category: "Vegetables" },
  { name: "Red cabbage", category: "Vegetables" },
  { name: "Frozen vegetables", category: "Vegetables" },
  { name: "Milk", category: "Dairy" },
  { name: "Eggs", category: "Dairy" },
  { name: "Drinking yogurt", category: "Dairy" },
  { name: "Greek yogurt", category: "Dairy" },
  { name: "Grated parmesan", category: "Dairy" },
  { name: "Cheese platter", category: "Dairy" },
  { name: "Mozzarella", category: "Dairy" },
  { name: "Canned tuna", category: "Canned" },
  { name: "Pork liver pâté", category: "Canned" },
  { name: "Canned corn", category: "Canned" },
  { name: "Bean stew", category: "Canned" },
  { name: "Canned beans", category: "Canned" },
  { name: "Salami", category: "Meat" },
  { name: "Frankfurters", category: "Meat" },
  { name: "Fish roe salad", category: "Meat" },
  { name: "Chicken parts", category: "Meat" },
  { name: "Chicken breast", category: "Meat" },
  { name: "Chicken legs", category: "Meat" },
  { name: "Toothpaste", category: "Cosmetics" },
  { name: "Toothbrush", category: "Cosmetics" },
  { name: "Shower gel", category: "Cosmetics" },
  { name: "Shampoo", category: "Cosmetics" },
  { name: "Liquid soap refill", category: "Cosmetics" },
  { name: "Natural bar soap", category: "Cosmetics" },
  { name: "Toilet paper", category: "Hygiene" },
  { name: "Paper towels", category: "Hygiene" },
  { name: "Tampons", category: "Hygiene" },
  { name: "Large trash bags", category: "Hygiene" },
  { name: "Small trash bags", category: "Hygiene" },
  { name: "Dishwasher rinse aid", category: "Appliances" },
  { name: "Dishwasher detergent", category: "Appliances" },
  { name: "Laundry detergent", category: "Appliances" },
  { name: "Fabric softener", category: "Appliances" },
  { name: "AAA batteries", category: "Appliances" },
  { name: "AA batteries", category: "Appliances" },
  { name: "Dish soap", category: "Detergents" },
  { name: "Laundry detergent", category: "Detergents" },
  { name: "Bleach", category: "Detergents" },
  { name: "Windshield washer fluid", category: "Detergents" },
  { name: "Windshield de-icer", category: "Detergents" },
  { name: "Parquet cleaner", category: "Detergents" },
  { name: "Surface disinfectant", category: "Detergents" },
  { name: "Sparkling water", category: "Drinks" },
  { name: "Still water", category: "Drinks" },
  { name: "Cola", category: "Drinks" },
  { name: "Orange juice", category: "Drinks" },
  { name: "Juice", category: "Drinks" },
  { name: "Green tea", category: "Drinks" },
  { name: "Fruit tea", category: "Drinks" },
  { name: "Coffee", category: "Drinks" },
  { name: "Flour", category: "Cooking" },
  { name: "Cornmeal", category: "Cooking" },
  { name: "Sunflower oil", category: "Cooking" },
  { name: "Olive oil", category: "Cooking" },
  { name: "Vinegar", category: "Cooking" },
  { name: "Balsamic vinegar", category: "Cooking" },
  { name: "Salt", category: "Cooking" },
  { name: "Pepper", category: "Cooking" },
  { name: "Honey", category: "Cooking" },
  { name: "Rice", category: "Pasta" },
  { name: "Couscous", category: "Pasta" },
  { name: "Whole wheat penne", category: "Pasta" },
  { name: "Spaghetti", category: "Pasta" },
  { name: "Vermicelli", category: "Pasta" },
  { name: "Canned dog food", category: "Pets" },
  { name: "Dry dog food", category: "Pets" },
  { name: "Dog shampoo", category: "Pets" },
  { name: "Dog pads", category: "Pets" },
];
